<a href="https://colab.research.google.com/github/AditiCoderElite/Mind-Reading-Machine-Based-Algorithm/blob/main/Mind_Reading_Machine_Based_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Mind Reading Machine Based Algorithm




---

In this algorithm:

1. The computer looks for certain patterns in the player inputs (`Heads` or `Tails`) and tries to remember them. Furthermore, it assumes that the player will follow these patterns the next time if the same situation arises.

2. If an assumed pattern is not repeated at least twice by the player, the machine predicts `Heads` or `Tails` randomly.

The types of patterns remembered, involve the outcome of two successive plays, i.e., whether or not the player won on those plays and whether the player changed their choice between the plays and after the plays.

There are 8 possible situations and, for each situation, a player can do two things. These 8 situations are:

1. The player **wins**, plays the **same** and **wins** again. The player then plays the same or plays differently.

2. The player **wins**, plays the **same** and **loses**. The player then plays the same or plays differently.

3. The player **wins**, plays **differently** and **wins** again. The player then plays the same or plays differently.

4. The player **wins**, plays **differently** and **loses**. The player then plays the same or plays differently.

5. The player **loses**, plays the **same** and **wins**. The player then plays the same or plays differently.

6. The player **loses**, plays the **same** and **loses** again. The player then plays the same or plays differently.

7. The player **loses**, plays **differently** and **wins**. The player then plays the same or plays differently.

8. The player **loses**, plays **differently** and **loses** again. The player then plays the same or plays differently.

Each situation corresponds to a different cell in the memory of a machine. Within a cell, two events are registered:

1. Whether the last time this situation arose, the player played the same or different.

2. Whether or not the behaviour indicated in the first point, was a repeat of the same behaviour in the preceding situation.



---

#### Last Two Players Inputs

The `last_1` and `last_2` variables keep track of the last two inputs of a player.

In [ ]:
last_1 = 0
last_2 = 0


- `last_1` stores the last player input.

- `last_2` stores the second-last player input.




---

#### The `inputs` Array

In [ ]:
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int)
inputs

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

The `inputs` array acts as a memory for the Mind Reader game.

- The first column (`column_index = 0`) of the `inputs` array will store the current player input.

- The second column (`column_index = 1`) will store whether a situation (out of the 8 possible situations) is repeated or not. The 8 possible situations are:

|Situation|Second-Last Play|Last Play|Current Player Input|
|-|-|-|-|
|1.|`0`|`0`|`0`|
|2.|`0`|`0`|`1`|
|3.|`0`|`1`|`0`|
|4.|`0`|`1`|`1`|
|5.|`1`|`0`|`0`|
|6.|`1`|`0`|`1`|
|7.|`1`|`1`|`0`|
|8.|`1`|`1`|`1`|

where `0` denotes `Heads` and `1` denotes `Tails`.

The blocks in the `inputs` array denote the second-last play.

- If `last_2 = 0`, then the `last_1` value will go to the first/second row of the **first** block.

- If `last_2 = 1`, then the `last_1` value will go to the first/second row of the **second** block.

<img src = 'https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/inputs_array.png' width=600>

At a time, the **current player input** will either go to the first block or second block because the second-last play would either be `0` or `1`.

Here are the possible ways in which the current player inputs will be recorded in the first block.

1. All the items in the first column are `0`.

  ```
  [[0, is_a_repeat],
    [0, is_a_repeat]]
  ```

2. The item in the first row and first column is `0` but the item in the second row and the first column is `1`.

  ```
  [[0, is_a_repeat],
    [1, is_a_repeat]]
  ```

3. The item in the first row and first column is `1` but the item in the second row and the first column is `0`.

  ```
  [[1, is_a_repeat],
    [0, is_a_repeat]]
  ```

4. All the items in the first column are `1`.

  ```
  [[1, is_a_repeat],
    [1, is_a_repeat]]
  ```

The value of `is_a_repeat` is either `0` or `1`.

  - The value `0` or `1` in the first column represents whether the player played `Heads` or `Tails`, respectively, in the last attempt.
  
  - The value `0` or `1` in the second column represents whether a situation (a combination of `last_2, last_1` and current player input) is repeated or not. The value `0` means the situation is NOT repeated and `1` means the situation is repeated.

The second block will also have the exact same possibilities.

---

#### The `update_inputs()` Function



In [ ]:
def update_inputs(current):
  if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1
    inputs[last_2][last_1][0] = current
  else:
    inputs[last_2][last_1][1] = 0
    inputs[last_2][last_1][0] = current

  last_2 = last_1
  last_1 = current

---

#### The `prediction()` Function



In [ ]:
def prediction():
  if inputs[last_2][last_1][1] == 1:
    predict = inputs[last_2][last_1][0]
  else:
    predict = random.randint(0, 1)
  return predict

---

####The `update_scores()` Function



In [ ]:
scores = [0, 0] # [computer_score, player_score]

def update_scores(predicted, player_input):
  if predicted == player_input:
    scores[0] =  scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) # The '\n' is called a newline character. It adds an empty newline.

  else:
    scores[1] = scores[1] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1])

---

#### The `reset()` Function



In [ ]:
def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0

  for i in range(len(scores)):
    scores[i] = 0

---

#### Putting Everything Together



In [ ]:
import random
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int)

last_1 = 0
last_2 = 0

scores = [0, 0] # [computer_score, player_score]

def update_inputs(current):
  global last_1, last_2
  if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1
    inputs[last_2][last_1][0] = current
  else:
    inputs[last_2][last_1][1] = 0
    inputs[last_2][last_1][0] = current

  last_2 = last_1 # last_1 becomes last_2
  last_1 = current # current becomes last_1, i.e., current -> last_1 -> last_2

def prediction():
  if inputs[last_2][last_1][1] == 1:
    predict = inputs[last_2][last_1][0]
  else:
    predict = random.randint(0, 1)
  return predict

def update_scores(predicted, player_input):
  if predicted == player_input:
    scores[0] = scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1])

  else:
    scores[1] = scores[1] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1])

def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0

  for i in range(2):
    scores[i] = 0

---

#### The `gameplay()` Function

In [ ]:
def gameplay():
  reset()
  print(inputs)
  print(scores)
  valid_entries = ['0', '1']
  while True:
    predicted = prediction()
    player_input = input("\nEnter either 1 or 0: ")

    while player_input not in valid_entries:
      print("\nInvalid Input!")
      player_input = input("Please enter either 1 or 0: ")

    player_input = int(player_input)
    update_inputs(player_input)
    update_scores(predicted, player_input)

    if scores[0] == 20:
      print("\nBad Luck, Computer Wins!\n")
      break

    elif scores[1] == 20:
      print("\nCongrats, You Won!\n")
      break

In [ ]:
gameplay()

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[0, 0]

Enter either 1 or 0: 0

Computer Score: 1 
Player Score: 0

Enter either 1 or 0: 0

Computer Score: 2 
Player Score: 0

Enter either 1 or 0: 0

Computer Score: 3 
Player Score: 0

Enter either 1 or 0: 1

Computer Score: 3 
Player Score: 1

Enter either 1 or 0: 1

Computer Score: 4 
Player Score: 1

Enter either 1 or 0: 1

Computer Score: 5 
Player Score: 1

Enter either 1 or 0: 1

Computer Score: 6 
Player Score: 1

Enter either 1 or 0: 0

Computer Score: 6 
Player Score: 2

Enter either 1 or 0: 

Invalid Input!
Please enter either 1 or 0: 

Invalid Input!
Please enter either 1 or 0: 0

Computer Score: 7 
Player Score: 2

Enter either 1 or 0: 1

Computer Score: 7 
Player Score: 3

Enter either 1 or 0: 0

Computer Score: 8 
Player Score: 3

Enter either 1 or 0: 0

Computer Score: 9 
Player Score: 3

Enter either 1 or 0: 0

Computer Score: 9 
Player Score: 4

Enter either 1 or 0: 1

Computer Score: 9 
Player Score: 5

Enter either 1 or 0: 1

Co

---